### ISSUE TITLE
PCA error on install

### ISSUE THREAD

**Issue by rasanderson** [vbonhomme/eigenfaces#1]
Trying to install using

devtools::install_github("vbonhomme/eigenfaces", build_vignettes=TRUE)

gives the error:

Error : object 'PCA' not found whilst loading namespace 'eigenfaces'

This is in RStudio 0.98.1087  R version 3.1.2

**Comment by rasanderson** [comment]
Problem is solved if the newest version of Momocs from github is installed instead of the version from CRAN.

**Comment by vbonhomme** [comment]
;-)

Thanks Roy. That's a really minimalist version, I will need it quite soon
(it the next year) and thus start to improve it. do not hesitate if you
have request, suggestions, or if you want to share code !

2015-10-21 17:51 GMT+02:00 Roy Sanderson notifications@github.com:

> Closed #1 https://github.com/vbonhomme/eigenfaces/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vbonhomme/eigenfaces/issues/1#event-441671840.

## 

vincentbonhomme.fr http://www.vincentbonhomme.fr

**Comment by rasanderson** [comment]
Thanks for putting together the packages: I’ve a final year undergraduate student doing a simple project on species identification from images, and I think your eigenfaces package might be quite useful for him.

**Comment by vbonhomme** [comment]
Well, I also have such things to try with eigen faces so perhaps we can
keep in touch. My email in on the homepage.

All the best,

Vincent

2015-10-22 9:45 GMT+02:00 Roy Sanderson notifications@github.com:

> Thanks for putting together the packages: I’ve a final year undergraduate
> student doing a simple project on species identification from images, and I
> think your eigenfaces package might be quite useful for him.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vbonhomme/eigenfaces/issues/1#issuecomment-150135416.

## 

vincentbonhomme.fr http://www.vincentbonhomme.fr
